### PR TITLE
Reorganize and nest docs navigation for readability

### LINKED ISSUE #1112: Clean up docs navigation sidebar
I think we should reorder/add more nesting to the docs navigation sidebar, to make it easier to see the important pages. For example we could emphasise the top-level presets by moving the lower-level presets under a subfolder (at the moment it's a bit confusing to new users which presets they should be adding themselves vs happen to be used underneath).

https://master.neutrinojs.org

https://github.com/neutrinojs/neutrino/blob/47ae54ce544b256973adf7c97cca09b26ab6d507/mkdocs.yml#L21-L75

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #1112.

### CODE REVIEW

**Comment by eliperelman** [comment]
Love it, I'll revise.

**Comment by edmorley** [comment]
(The yellow highlights are things that are confusing since they have words in common)

**Comment by eliperelman** [comment]
@edmorley how's this?

screen shot 2018-09-19 at 4 55 19 pm

**Comment by eliperelman** [comment]
w00t

**Comment by timkelty** [comment]
Great job, guys!

**Pull request merged**
