### PR TITLE
Add neutrino --inspect support for alternative config filenames

### PR DESCRIPTION
**Pull request by SilvaQ**
the inspect command supports specifying a configuration file #1609

### CODE REVIEW

**Review by edmorley — CHANGES_REQUESTED** [review]
Hi! Thank you for the PR - sorry for the delayed review.

Could you also document this here:
https://neutrinojs.org/usage/#inspecting-the-generated-webpack-config
https://github.com/neutrinojs/neutrino/blob/master/docs/usage.md#inspecting-the-generated-webpack-config

**Comment by SilvaQ** [comment]
> Hi! Thank you for the PR - sorry for the delayed review.
> 
> Could you also document this here:
> https://neutrinojs.org/usage/#inspecting-the-generated-webpack-config
> https://github.com/neutrinojs/neutrino/blob/master/docs/usage.md#inspecting-the-generated-webpack-config

Hi @edmorley 
I use translation software to translate my language into English, so if I continue to translate and supplement the documentation, will the content of this machine translation affect the user's understanding? And I don't have a better explanation for this feature.

Do we have any better options for solving this difficulty?

**Comment by edmorley** [comment]
@SilvaQ Ah no problem - I can suggest a wording.

In that section of the documentation, replace this:

````
Or:

```bash
NODE_ENV={production,development,test} neutrino --inspect
```
````

With:

````
Or:

```bash
NODE_ENV={production,development,test} neutrino --inspect
```

If your Neutrino configuration file is not named `.neutrinojs.js`, specify the filename using `--config`. For example:

```bash
neutrino --inspect --mode {production,development} --config .custom.neutrino.config.js
```
````

**Review by edmorley — APPROVED** [review]
Thank you :-)

**Comment by edmorley** [comment]
I'll publish a new Neutrino release sometime this week :-)

**Comment by edmorley** [comment]
Sorry for the delay - this has now been published in Neutrino v9.5.0 :-)

**Pull request merged**
