### PR TITLE
Generating gitignore at project creation

### PR DESCRIPTION
**Pull request by rajatsharma**

### CODE REVIEW

**Comment by eliperelman** [comment]
I'm skeptical of forcing this to output a gitignore file, especially since there are other version control systems that Neutrino users are using. What if we instead recommended them running a command to output most of the relevant gitignore content, and adding Neutrino specifics like the `build` directory?

```bash
# From https://www.npmjs.com/package/gitignore
npx gitignore node
```

**Comment by edmorley** [comment]
I'm happy with that or wontfixing #1197 too.

**Comment by eliperelman** [comment]
OK, I think we can generate this for them since git is much more prevalent and a conversion to hgignore should be as easy as a file rename. I'll add a relevant review.

**Comment by eliperelman** [comment]
Resolved in #1340.

**Pull request closed without merging**
